integrating backend
amansethi00/yummy-basket pull request #1
Opened 2021-05-06 18:30 UTC by amansethi00

2021-05-09 07:16 UTC, tonnyvijayan reviewed
Great work so far, Aman. I've left a few suggestions below.

2021-05-09 07:16 UTC, tonnyvijayan commented on backend/ecom/index.js
> +// error handler
You could try to extract out the error and 404 handler middleware out into a separate file.

2021-05-09 07:16 UTC, tonnyvijayan commented on src/App.jsx
> +      <nav className="nav" style={{backgroundColor:selectedTheme[theme].bg,color:selectedTheme[theme].color}} >
You can try to extract out these components into separate files, maybe also  have another component that will list all the routes, and then just have that component here in the app.js file along with the navbar component

2021-05-09 07:16 UTC, tonnyvijayan commented on src/components/Cart/CartList.js
> +          {filteredCart.reduce(
You could move the reduce method  outside and just call the final value here

2021-05-15 09:04 UTC, Dev-kunal commented
Great work Aman..!
I have some suggestions regarding UX and noticed some bugs.

- When a user try to add product to cart or wishlists an item without logging in, you should redirect him to login OR if youre 
 maintaining user actions without login then you should show a popup regarding the action.
- Also when i refresh a page "404page not found error appears from netlify" it maybe due to router.
- The cart value becomes Nan after adding more than one item in cart.
- I was not able to remove the product from wishlist page

2021-05-24 18:17 UTC, im-rhlrvndrn requested changes

2021-05-24 18:17 UTC, imrhlrvndrn commented on backend/ecom/db.connect.js
> +      const db= await mongoose.connect(`mongodb+srv://sethgAdmin:${myPassword}@sethg-cluster.kgrbn.mongodb.net/Ecom?retryWrites=true&w=majority`,{useNewUrlParser: true, useUnifiedTopology: true} )
Shift the entire MongoDB connection URL to the `.env` file and name it `MONGODB_URI`

2021-05-24 18:17 UTC, imrhlrvndrn commented on backend/ecom/middleware/auth.midlleware.js
> +const authMiddleware = async(req, res, next) => {
After the JWT Auth session, this implementation will be changed since you're **decoding** the token and retrieving the `userId` from the token. You'll just pass the `userId` in the `req.auth`. 

**Note:** I'm not adding the decoded token details to `req.user` because in the `/users` route you might pass the user details in the `route.param()` and you don't want to mix it up

2021-05-24 18:17 UTC, imrhlrvndrn commented on backend/ecom/model/products.model.js
> +const Product = mongoose.model('Product',productSchema);
# Implement this suggestion in all the `*.model.js` files

```suggestion
module.exports = mongoose.model('Product', productSchema)
```

2021-05-24 18:17 UTC, imrhlrvndrn commented on backend/ecom/model/user.model.js
> +const express = require('express');
Use the **[Prettier VS code extension](https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode)** for proper spacing and indentation

2021-05-24 18:17 UTC, imrhlrvndrn commented on backend/ecom/model/user.model.js
> +  addressId:{
I don't think you need another collection for maintaining `Address`, a user would at most have 5 simultaneous addresses which can be stored in the user Schema itself. It's an unnecessary DB call

2021-05-24 18:17 UTC, imrhlrvndrn commented on backend/ecom/model/wishlist.model.js
> +  products: [{ type: mongoose.ObjectId, ref: 'Product' }]
If the `products` field is the only thing you're storing for **Wishlist** then you can shift this to the userSchema as well. These are unnecessary extra DB calls to fetch the wishlist with just the `products` field and then fetch all the products with the `_ids`

2021-05-24 18:17 UTC, imrhlrvndrn commented on backend/ecom/index.js
> +app.use('/wishlist',authMiddleware,wishlistRoute);
Making `/wishlist`, `/cart` and `/address` into plural will make more sense `/wishlists/:wishlistId` it'll say that from a collection of wishlists fetch details for the wishlist with the `ID === wishlistId`

2021-05-24 18:17 UTC, imrhlrvndrn commented on backend/ecom/routes/address.route.js
> +      res.json({ success: true, userAddresses });
When you're sending the response make sure you maintain consistency in the `response` format. Here your response is 

```
const response = {
    success: true,
    userAddresses
}
```

But in the POST request, your response is
```
const response = {
    success: true,
    updatedUserAddresses
}
```

This is a bad API design. I'm sure you'll remember which properties you're sending as response to the client but a good API design must have a consistent response format like
```
const response = {
    success: true,
    data: {
        addresses: userAddresses || updatedUserAddresses,
    }
}
```

The fields in `data` will vary depending on the request. Also, the field names must not be `userAddresses`, `updatedUserAddresses`, and so on. These names are great when limited to variable names. Response field names must be simple and declarative like `addresses`, `cart`, etc

2021-05-24 18:17 UTC, imrhlrvndrn commented on backend/ecom/routes/address.route.js
> +      const updatedUserAddresses = await Address.findOne({ _id: user.addressId }).populate('address');
You don't need to make another DB call to fetch the updated addresses of a user. After `line 22` the `userAddresses.address` will have the pushed address which you can simply send in the response and yes it'll contain the `_id` field and everything a saved address object would've. You may `console.log()` the output if you don't believe me ☻

```suggestion
res.json({ success: true, updatedUserAddresses: userAddresses.address });
```

2021-05-24 18:17 UTC, imrhlrvndrn commented on backend/ecom/routes/cart.route.js
> +      res.json({ success: true, products: productsInCart.products })
Change the `response` format

2021-05-24 18:17 UTC, imrhlrvndrn commented on backend/ecom/routes/cart.route.js
> +        const updatedCartInstancee = await Cart.findOne({ _id: req.user.cartId });
Again you don't need this DB call

2021-05-24 18:17 UTC, imrhlrvndrn commented on backend/ecom/routes/cart.route.js
> +        const updatedCartInstancee = await Cart.findOne({ _id: req.user.cartId });
Remove this call too

2021-05-24 18:17 UTC, imrhlrvndrn commented on backend/ecom/routes/cart.route.js
> +      const updatedCartInstance = await Cart.findOne({ _id: req.user.cartId });
Remove this DB call too

2021-05-24 18:17 UTC, imrhlrvndrn commented on backend/ecom/routes/cart.route.js
> +      res.json({ success: false, message: "not good" })
## The error `message` on each and every `catch` block could be more descriptive like `Couldn't delete the product` or something more relatable to the operation

2021-05-24 18:17 UTC, imrhlrvndrn commented on backend/ecom/routes/login.route.js
> +       res.json({success:true,user: req.user});
Change the `response` format

2021-05-24 18:17 UTC, imrhlrvndrn commented on backend/ecom/routes/login.route.js
> +    res.status(401).json({success:false,message:"please login to perform this action"})
The error message should be something like `Couldn't log in` because if the login operation fails the user doesn't have to be reminded that he/she has to log in to perform whatever action they were trying to perform

2021-05-24 18:17 UTC, imrhlrvndrn commented on backend/ecom/routes/products.route.js
> +      res.json({ success: true, message: "succesfully received products data", products: allProducts })
See here the `response` format is completely different, I didn't see the `message` field in any of the responses above this file. That's why you need a consistent response format

2021-05-24 18:17 UTC, imrhlrvndrn commented on backend/ecom/routes/signup.route.js
> +      res.json({ success: true, message: "testing ",user:newUser })
Change the response format and send a descriptive `message` in the response

2021-05-24 18:17 UTC, imrhlrvndrn commented on backend/ecom/routes/user.route.js
> +
Why is this file only 4 lines long?

2021-05-24 18:17 UTC, imrhlrvndrn commented on backend/ecom/routes/wishlist.route.js
> +        const updatedWishlist = await Wishlist.findOne({ _id: wishlistId });
Don't need the DB call and change the response format

2021-05-24 18:17 UTC, imrhlrvndrn commented on backend/ecom/routes/wishlist.route.js
> +      const updatedWishlist = await Wishlist.findOne({ _id: wishlistId }).populate('products');
Make the same changes as mentioned in the above request **METHOD**

2021-05-24 18:17 UTC, imrhlrvndrn commented on src/App.jsx
> +function App() {
The `App.jsx` must only contain the `<Routes>` and the `toast` extract the `nav` to a `<Nav/>` component

2021-05-24 18:17 UTC, imrhlrvndrn commented on src/components/Address/Address.js
> +export function Address() {
Convert this into an ES6 arrow function

2021-05-24 18:17 UTC, imrhlrvndrn commented on src/components/Button/IncDecButton.js
> +  const getCartItem = (id) => {
Convert the functions on `line 8 and 11` to one line ES6 function `()=> cart.filter(( prev ) => productId)[0]`

2021-05-24 18:17 UTC, imrhlrvndrn commented on src/components/Button/IncDecButton.js
> +        {
Look into [axios.create()](https://www.npmjs.com/package/axios#config-defaults) where you can configure the headers and it'll be sent on all the requests. Then you don't have to pass headers on individual requests

2021-05-24 18:17 UTC, imrhlrvndrn commented on src/components/Button/IncDecButton.js
> +            parseInt(
Adding `+` will convert the value to `Number`. Do the same on `line 57`. Although this implementation is also right

```suggestion
+cart.filter((prev) => prev?.productId?._id === product._id)[0].quantity + 1
```

2021-05-24 18:17 UTC, imrhlrvndrn commented on src/components/Cart/CartList.js
> +                ></img>
Images are self-closing tags => `<img/>`

2021-05-24 18:17 UTC, imrhlrvndrn commented on src/components/Home/Login.js
> +          <span class="input-grp-text">username</span>
Always use `<label>` with `<inputs />`

```
<label htmlFor='input-username'>username</label>
<input id='' placeholder='Enter your username here' />
```

This will allow the user to click on the label text and focus the input field. It's better for UX

2021-05-24 18:17 UTC, imrhlrvndrn commented on src/components/Home/Login.js
> +      <button
For login and signup forms use the `<form>` tag convert this `<button>` to `<button type='submit'>` and pass the `loginHandler` function to the form like this `<form onSubmit={loginHandler}>`. Now the user can just click **Enter** and the form will be submitted. Don't make the user manually use the mouse and click the **Login/Signup** button when they can use the keyboard for it

2021-05-24 18:17 UTC, imrhlrvndrn commented on src/components/Home/Signup.js
> +        {
Use the `axios.create()` I suggested before

2021-05-24 18:17 UTC, imrhlrvndrn commented on src/components/Home/Signup.js
> +import React, {useRef, useState} from "react";
## Implement all the changes suggested in the `Login.js` component

2021-05-24 18:17 UTC, imrhlrvndrn commented on src/components/Product/ProductList.js
> +    const anonFun = async () => {
Extract the API call into a function `fetchCart()`. Do the same for the wishlist API call and call both the functions in one `useEffect` using an **IIFE**

```suggestion
( 
    async () => {
        await fetchCart() 
        await fetchWishlist()
    }
)()
```

2021-05-24 18:17 UTC, im-rhlrvndrn commented on src/components/Product/ProductList.js
> +  useEffect(() => {
Extract the `useEffect` functions outside and use an **IIFE** in the useEffect

```
useEffect(()=>{
    (async ()=> {
        await fetchProducts();
        await getAndSetCart();
        await getAndSetWishlist();
    })()
}, [])
```

2021-05-24 18:17 UTC, im-rhlrvndrn commented on src/context/cart-context.js
> +  const [value, dispatch] = useReducer(reducer, {
extract the `reducer` and `initialState` into separate file named `cart.reducer.js` and import them in this file

```suggestion
const [state, dispatch] = useReducer( reducer, initialState );
```

2022-02-11 19:23 UTC, merged